---
name: CI
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
    inputs:
      build_blade:
        description: Build Blade
        type: boolean
        default: true
      lint:
        description: Lint
        type: boolean
        default: true
      unit_test:
        description: Unit Tests
        type: boolean
        default: true
      e2e_polybft_test:
        description: E2E PolyBFT Tests
        type: boolean
        default: true
      e2e_legacy_test:
        description: E2E Legacy Tests
        type: boolean
        default: true
      property_polybft_test:
        description: Property PolyBFT Tests
        type: boolean
        default: true
      fuzz_test:
        description: Fuzz Tests
        type: boolean
        default: true
      benchmark_test:
        description: Benchmark Tests
        type: boolean
        default: true
  workflow_call:
    inputs:
      build_blade:
        description: Build Blade
        type: boolean
      lint:
        description: Lint
        type: boolean
        required: true
      unit_test:
        description: Unit Tests
        type: boolean
        required: true
      e2e_polybft_test:
        description: E2E PolyBFT Tests
        type: boolean
        required: true
      e2e_legacy_test:
        description: E2E Legacy Tests
        type: boolean
        required: true
      property_polybft_test:
        description: Property PolyBFT Tests
        type: boolean
        required: true
      fuzz_test:
        description: Fuzz Tests
        type: boolean
        required: true
      benchmark_test:
        description: Benchmark Tests
        type: boolean
        required: true
    outputs:
      build_blade:
        description: Build Blade output
        value: ${{ jobs.build_blade.outputs.workflow_output }}
      lint:
        description: Lint output
        value: ${{ jobs.lint.outputs.workflow_output }}
      unit_test:
        description: Unit Tests output
        value: ${{ jobs.unit_test.outputs.workflow_output }}
      e2e_polybft_test:
        description: E2E PolyBFT Tests output
        value: ${{ jobs.e2e_polybft_test.outputs.workflow_output }}
      e2e_legacy_test:
        description: E2E Legacy Tests output
        value: ${{ jobs.e2e_legacy_test.outputs.workflow_output }}
      property_polybft_test:
        description: Property PolyBFT Tests output
        value: ${{ jobs.property_polybft_test.outputs.workflow_output }}
      fuzz_test:
        description: Fuzz Tests output
        value: ${{ jobs.fuzz_test.outputs.workflow_output }}
      benchmark_test:
        description: Benchmark Tests output
        value: ${{ jobs.benchmark_test.outputs.workflow_output }}

jobs:
  build_blade:
    name: Build Blade
    uses: ./.github/workflows/build.yml
    if: |
      inputs.build_blade || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: build_blade
    if: |
      inputs.lint || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  unit_test:
    name: Unit Tests
    uses: ./.github/workflows/unit-test.yml
    needs: build_blade
    if: |
      inputs.unit_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  e2e_polybft_test:
    name: E2E PolyBFT Tests
    uses: ./.github/workflows/e2e-polybft-test.yml
    needs: build_blade
    if: |
      inputs.e2e_polybft_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  e2e_legacy_test:
    name: E2E Legacy Tests
    uses: ./.github/workflows/e2e-legacy-test.yml
    needs: build_blade
    if: |
      inputs.e2e_legacy_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  property_polybft_test:
    name: Property PolyBFT Tests
    uses: ./.github/workflows/property-polybft-test.yml
    needs: build_blade
    if: |
      inputs.property_polybft_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  fuzz_test:
    name: Fuzz Tests
    uses: ./.github/workflows/fuzz-test.yml
    needs: build_blade
    if: |
      inputs.fuzz_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  benchmark_test:
    name: Benchmark Tests
    uses: ./.github/workflows/benchmark-test.yml
    needs: build_blade
    if: |
      inputs.benchmark_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
